
# Download a website:
alias get-webpage='wget -p -k'
alias clone-website='wget --recursive --convert-links --adjust-extension --page-requisites'

# Ruby server:
alias share-public='ruby -run -ehttpd ~/Public/ -p8000'
alias share-folder='ruby -run -ehttpd . -p8000'
